---
apiVersion: v1                     
kind: Namespace
metadata:
  name: eda
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eda-instance
  namespace: eda
  labels:
      app: eda-instance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eda-instance
  template:
    metadata:
      labels:
        app: eda-instance
    spec:
      containers:
      - image: niklaushirt/eda-container:0.1
        imagePullPolicy: IfNotPresent
        name: eda-instance
        command:
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "250m"
            memory: "250Mi"
        env:
        - name: REPO_URL
          value: https://github.com/niklaushirt/cp4waiops-eda.git
---


