apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eda-server
  name: eda-server
  namespace: eda-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eda-server
  strategy: {}
  template:
    metadata:
      labels:
        app: eda-server
    spec:
      containers:
      - args:
        - /bin/bash
        - -c
        - alembic upgrade head && eda-server
        env:
        - name: EDA_DATABASE_URL
          value: postgresql+asyncpg://postgres:secret@postgres/eda_server
        - name: EDA_HOST
          value: 0.0.0.0
        image: niklaushirt/eda-server:0.1
        imagePullPolicy: IfNotPresent
        name: eda-server
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccount: eda-admin

status: {}
