apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: eda-postgres
  name: postgres-data
  namespace: eda-server
spec:
  storageClassName: ibmc-file-gold-gid
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
