apiVersion: v1
kind: Service
metadata:
  labels:
    app: eda-server
  name: eda-server
  namespace: eda-server
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    app: eda-server
status:
  loadBalancer: {}
